print("Ingrese sus datos: ")
nmb = input("¿Cuál es su nombre? ")
apld = input("¿Cuál es su appelido? ")
edad = int(input("Ingrese su edad "))
sexo = input("Ingrese su sexo ")
ocp = input("Ingrese su ocupación ")
sal = int(input("Ingrese su salario "))

print("")
print("Estos son sus datos:")
print("Nombre:", nmb)
print("Apellido:", apld)
print("Edad:", edad)
print("Sexo:", sexo)
print("Ocupación:", ocp)
print("Salario:", sal)
